### PR TITLE
implemented handling for app credentials that changed some attributes…

### PR DESCRIPTION
**Pull request by gcornacchia**
… (create or update) + automatic test

Hi @cwiechmann,
I noticed that during the import of applications a scenario wasn't implemented.

If I change some attributes in an already imported app credential (like client secret or corsOrigins) the apim-cli tool always tried to recreate the credential resource (oauth, extclients or apikey). With this pull request I tried to develop this scenario handling the creating or updating of the resource (if already exists).

Take a look and let me know

### CODE REVIEW

**Comment by gcornacchia** [comment]
hi @cwiechmann , news?

**Comment by cwiechmann** [comment]
Hi @gcornacchia, sorry for not coming back earlier. I'm super busy with another project: https://github.com/Axway-API-Management-Plus/apigateway-openlogging-elk and on top of that, Travis-CI has decided to not support Open-Source projects anymore. Hence, I have currently no visibility about the impact of changes. 
Not an issue, as we will pay for it, but unfortunately it has to wait a bit.

**Comment by gcornacchia** [comment]
hi @cwiechmann, we really need this feature for migrating data from 7.6.2 to 7.7 installation, when do you think you can check this code?

**Comment by cwiechmann** [comment]
@gcornacchia, Yesterday evening I finished my work on the other project so I will focus on this again. Expect feedback until the end of this week.

**Review by cwiechmann — APPROVED** [review]
Looks all good to me. And also Travis-CI reports no error.

**Comment by cwiechmann** [comment]
Thanks for your patience @gcornacchia and your help with this PR. Will merge it now.

**Pull request merged**
